---
name: "Generate CHANGELOG"

on:
  workflow_call:
    secrets:
      CHANGELOG_PAT:
        required: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHANGELOG_PAT }}
          fetch-depth: 0
          submodules: false
          ref: main
      - name: Generate Changelog
        uses: orange-cloudavenue/generate-changelog-action@v0.1.9
      - name: Commit and push changes
        uses: orange-cloudavenue/workflows/.github/workflows/git/bot-commit.yml@main
        inputs:
          commit-message: "chore: Update CHANGELOG.md"
          file-pattern: CHANGELOG.md