name: "Bot commit"
on:
  workflow_call:
    secrets:
        CHANGELOG_PAT:
          required: true
    inputs:
        commit-message:
            description: 'Commit message (follows conventional commit format)'
            required: true
            type: string
        file-pattern:
            description: 'File pattern (Eg: CHANGELOG.md)'
            type: string
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
        - if: inputs.file-pattern != ''
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: ${{ inputs.commit-message }}
            commit_options: '--no-verify --signoff'
            file_pattern: ${{ inputs.file-pattern }}
            commit_user_name: github-actions[bot]
            commit_user_email: github-actions[bot]@users.noreply.github.com
            commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        - if: inputs.file-pattern == ''
            uses: stefanzweifel/git-auto-commit-action@v5
            with:
                commit_message: ${{ inputs.commit-message }}
                commit_options: '--no-verify --signoff'
                commit_user_name: github-actions[bot]
                commit_user_email: github-actions[bot]@users.noreply.github.com
                commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>