name: "Generate CHANGELOG"

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

permissions:
  contents: write

jobs:
  generate-changelog:
    name: "Generate Changelog"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          submodules: false
          ref: main
      - name: Script to generate changelog
        uses: orange-cloudavenue/generate-changelog-action@b9fdb410d3a674a03aee45472d9ff769b7c75bc1
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          branch: main
          commit_message: "chore: Update CHANGELOG.md"
          commit_options: '--no-verify --signoff'
          file_pattern: CHANGELOG.md
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
