name: "Generate new version"
on:
  workflow_call:
    secrets:
        TOKEN:
          required: true
    inputs:
        tag:
            description: 'Tag version number (Eg: v0.1.0)'
            required: true
            type: string
            
jobs:
  check:
    runs-on: arc-runners
    steps:
      - uses: actions/checkout@v4
        name: Checkout 
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          ref: main
      - name: Update Changelog Header
        run: |
          CHANGELOG_FILE_NAME="CHANGELOG.md"
          RELEASE_TAG=${{ inputs.tag }}

          # Add Release Date
          RELEASE_DATE=`date +%B' '%e', '%Y`
          sed -i -e "1 s/.*Unreleased.*/## ${RELEASE_TAG#v} ($RELEASE_DATE)/" $CHANGELOG_FILE_NAME

          # Prepend next release line
          echo Release is: $RELEASE_TAG

          NEW_RELEASE_LINE=$(echo $RELEASE_TAG | awk -F. '{
              $1 = substr($1,2)
              $2 += 1
              printf("%s.%01d.0\n\n", $1, $2);
          }')

          echo New minor version is: v$NEW_RELEASE_LINE

          echo -e "## $NEW_RELEASE_LINE (Unreleased)\n$(cat $CHANGELOG_FILE_NAME)" > $CHANGELOG_FILE_NAME
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update CHANGELOG.md"
          commit_options: '--no-verify --signoff'
          file_pattern: CHANGELOG.md
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
