name: "Publish documentation on GitHub Pages"

on:
  workflow_call:
    inputs:
      plugins:
        type: string
        description: "List of plugins to install separated by space"
        required: false
        default: ""
      ref:
        description: "Git reference to checkout"
        required: true
        type: string
      repository:
        description: "Repository to checkout"
        required: true
        type: string

permissions:
  contents: write

jobs:
  check-publish-requirements:
    runs-on: ubuntu-latest
    outputs:
      need-publish: ${{ steps.filter.outputs.files_exists }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - name: 'Check File Existence'
        id: filter
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029
        with:
          files: 'mkdocs.yml'

  publish-doc:
    if: ${{ needs.check-publish-requirements.outputs.need-publish == 'true' }}
    needs: check-publish-requirements
    name: github page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - name: Configure Git Credentials
        run: |
          git config user.name cloudavenue-docs-bot
          git config user.email 205752564+cloudavenue-bot@users.noreply.github.com
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  #v6.1.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-literate-nav ${{ inputs.plugins }}
      - run: mkdocs gh-deploy --force
