name: "Update Documentation"

on:
  workflow_call:
    inputs:
      plugins:
        type: string
        description: "List of plugins to install separated by space"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  check-publish-requirements:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      need-publish: ${{ steps.filter.outputs.doc }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            doc:
              - docs/**'
              - 'mkdocs.yml'

  publish-doc:
    if: ${{ needs.check-publish-requirements.outputs.need-publish == 'true' || github.event_name == 'workflow_dispatch' }}
    needs: check-publish-requirements
    name: github page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-literate-nav ${{ inputs.plugins }}
      - run: mkdocs gh-deploy --force