name: "Request doc update"

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

jobs:
  request-update:
    name: "Trigger"
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TOKEN }}
          repository: orange-cloudavenue/orange-cloudavenue.github.io
          event-type: update-doc
