---
name: "Generate CHANGELOG"

"on":
  workflow_call:
    secrets:
      CHANGELOG_PAT:
        required: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.CHANGELOG_PAT }}
          fetch-depth: 0
          submodules: false
          ref: main
      - uses: orange-cloudavenue/generate-changelog-action@v0.1.9
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "chore: Update CHANGELOG.md"
          commit_options: '--no-verify --signoff'
          push_options: '--force'
          file_pattern: CHANGELOG.md
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: Changelog Bot <github-actions[bot]@users.noreply.github.com>