name: "Go report card"

on:
  workflow_call:
  
permissions:
  contents: read
  
jobs:
  refresh-go-report-card:
    runs-on: ubuntu-latest
    name: "Refresh"
    steps:
      -         uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9