name: "Go report card"

on:
  workflow_call:
  
permissions:
  contents: read
  
jobs:
  refresh-go-report-card:
    runs-on: arc-runners
    name: "Refresh"
    steps:
      - uses: creekorful/goreportcard-action@v1.0