name: "Go report card"

on:
  workflow_call:
  
permissions:
  contents: read
  
jobs:
  check-lint-requirements:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: creekorful/goreportcard-action@v1.0