name: "Golang Unit Test"

on:
  workflow_call:
    inputs:
      send-coverage:
        description: 'Send coverage to coveralls'
        required: false
        type: boolean
      ref:
        description: 'Git reference to checkout (eg: {{github.ref}})'
        required: true
        type: string
      repository:
        description: 'Repository to checkout (eg: {{github.repository}})'
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-test-requirements:
    name: Check test requirements
    runs-on: arc-runners
    outputs:
      need-test: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'

  tests:
    needs: check-test-requirements
    if: ${{ needs.check-test-requirements.outputs.need-test == 'true' }}
    name: Run tests and send coverage
    runs-on: arc-runners
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.23'
          - '1.22'
          - '1.21'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies & run tests
        shell: bash 
        run: find . -name go.mod -execdir pwd \; | xargs -I {} bash -c 'cd {} && go mod download && go test -v -coverprofile=profile.cov ./...'
      
      - name: Coveralls Parallel
        if: inputs.send-coverage == true
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          file: profile.cov

  # notifies that all test jobs are finished.
  coverage-finish:
    needs: tests
    if: ${{ inputs.send-coverage == true && always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "run-${{ join(needs.test.outputs.matrix.go, '-') }}"