name: "Golang Unit Test"

on:
  workflow_call:
    inputs:
      send-coverage:
        description: 'Send coverage to coveralls'
        required: false
        type: boolean
      ref:
        description: 'Git reference to checkout (eg: {{github.ref}})'
        required: true
        type: string
      repository:
        description: 'Repository to checkout (eg: {{github.repository}})'
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-test-requirements:
    name: Check test requirements
    runs-on: arc-runners
    outputs:
      need-test: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'

  coverage:
    needs: check-test-requirements
    if: ${{ needs.check-test-requirements.outputs.need-test == 'true' }}
    name: Run tests and send coverage
    runs-on: arc-runners
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.23'
          - '1.22'
          - '1.21'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies & run tests
        shell: bash 
        run: find . -name go.mod -execdir pwd \; | xargs -I {} bash -c 'cd {} && go mod download && go test -v -coverprofile=profile.cov ./...'
      - if: inputs.send-coverage == 'true'
        name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}
          parallel: true

  # notifies that all test jobs are finished.
  coverage-finish:
    if: inputs.send-covegage == 'true'
    needs: coverage
    runs-on: arc-runners
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true