name: "Golang Unit Test Terraform Provider"

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to checkout (eg: {{github.ref}})'
        required: true
        type: string
      repository:
        description: 'Repository to checkout (eg: {{github.repository}})'
        required: true
        type: string
    secrets:
      CLOUDAVENUE_ORG:
        required: true
      CLOUDAVENUE_USER:
        required: true
      CLOUDAVENUE_PASSWORD:
        required: true
      CLOUDAVENUE_VDC:
        required: true

permissions:
  contents: read

jobs:
  check-test-requirements:
    name: Check test requirements
    runs-on: arc-runners
    outputs:
      need-test: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'

  testsunit:
    name: Run unit tests
    needs: check-test-requirements
    if: ${{ needs.check-test-requirements.outputs.need-test == 'true' }}
    runs-on: arc-runners
    steps:
      # https://github.com/actions/setup-go/issues/424#issuecomment-2796487736
      - name: Setup tar default options
        shell: bash
        run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - name: Run Go unit tests
        env:
          TEST_CLOUDAVENUE_ORG: ${{ secrets.CLOUDAVENUE_ORG }}
          TEST_CLOUDAVENUE_USERNAME: ${{ secrets.CLOUDAVENUE_USER }}
          TEST_CLOUDAVENUE_PASSWORD: ${{ secrets.CLOUDAVENUE_PASSWORD }}
          TEST_CLOUDAVENUE_VDC: ${{ secrets.CLOUDAVENUE_VDC }}
        run: |
          go test $(go list ./... | grep -v /internal/testsacc)