name: "Golang Unit Test"

on:
  workflow_call:
    inputs:
      send-covegage:
        description: 'Send coverage to coveralls'
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  check-test-requirements:
    runs-on: arc-runners
    outputs:
      need-test: ${{ steps.filter.outputs.go }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            go:
              - '**/*.go'
              - 'go.mod'

  coverage:
    needs: check-test-requirements
    if: ${{ needs.check-test-requirements.outputs.need-test == 'true' }}
    runs-on: arc-runners
    strategy:
      fail-fast: false
      matrix:
        go:
          - '1.23'
          - '1.22'
          - '1.21'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        shell: bash 
        run: go mod download
      - run: go test -v -coverprofile=profile.cov ./...
      - if: inputs.send-covegage == 'true'
        name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}
          parallel: true

  # notifies that all test jobs are finished.
  coverage-finish:
    if: inputs.send-covegage == 'true'
    needs: coverage
    runs-on: arc-runners
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true