name: Plumber

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  plumber:
    name: "Plumber CI/CD Security Scan"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        with:
          persist-credentials: false
      - uses: getplumber/plumber@c85c712bca3c9f547a88c66bb2541db179a1a79e
        with:
          min-score: A
