name: "PR Auto Assign"

on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: [self-hosted, Linux]
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1