name: "License Check"

on:
  workflow_call:

permissions:
  pull-requests: write
  contents: write

jobs:
  header-license:
    name: "Check License Header"
    runs-on: [self-hosted, Linux]
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - run: go install github.com/apache/skywalking-eyes/cmd/license-eye@latest

      - run: license-eye header fix

      - name: Check if any files changed
        id: changed-files
        run: |
          git diff --exit-code || echo "::set-output name=any_changed::true"

      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update License Headers"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
