name: "PR Size"

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to checkout (eg: {{github.ref}})'
        required: true
        type: string
      repository:
        description: 'Repository to checkout (eg: {{github.repository}})'
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-label-size:
    name: "Calculate PR Size"
    runs-on: arc-runners
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - name: Label PR based on size
        uses: cbrgm/pr-size-labeler-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          github_repository: ${{ github.repository }} 
          github_pr_number: ${{ github.event.number }} 
          config_file_path: '.github/pull-request-size.yml'
