name: "License Check"

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to checkout (eg: {{github.ref}})'
        required: true
        type: string
      repository:
        description: 'Repository to checkout (eg: {{github.repository}})'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  header-license:
    name: "Check License Header"
    runs-on: ubuntu-latest
    # Not run on draft PRs or PRs from forks or dependabot
    if: |
       github.event.pull_request.draft == false &&
       ! github.event.pull_request.head.repo.fork &&
       github.actor != 'dependabot[bot]'
    steps:
      # https://github.com/actions/setup-go/issues/424#issuecomment-2796487736
      - name: Setup tar default options
        shell: bash
        run: echo "TAR_OPTIONS=--skip-old-files" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install reuse
        run: |
          curl -sSL https://github.com/fsfe/reuse-tool/releases/latest/download/reuse-linux-amd64 -o /usr/local/bin/reuse
          chmod +x /usr/local/bin/reuse

      - name: Fix old license identifiers
        run: |
          find . -type f \( -name "*.go" -o -name "*.yml" -o -name "*.yaml" -o -name "*.njk" -o -name "*.tmpl" \) \
            -not -path "./.git/*" \
            -exec sed -i -e 's/Mozilla Public License 2\.0/MPL-2.0/g' -e 's/Apache License 2\.0/Apache-2.0/g' {} +

      - run: reuse annotate --recursive

      - name: Check if any files changed
        id: changed-files
        run: |
          git diff --exit-code || echo "any_changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d
        with:
          commit_message: "chore: Update License Headers"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
