name: "PR Size"

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true

permissions:
  pull-requests: write

jobs:
  auto-label-size:
    name: "Calculate PR Size"
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      - name: Label PR based on size
        uses: cbrgm/pr-size-labeler-action@main
        with:
          github_token: ${{ secrets.TOKEN }} 
          github_repository: ${{ github.repository }} 
          github_pr_number: ${{ github.event.number }} 
          config_file_path: '.github/pull-request-size.yml'
