name: Add issue/PR to project

on:
  workflow_call:
    secrets:
        TOKEN:
          required: true

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue/PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/orange-cloudavenue/projects/12
          github-token: ${{ secrets.TOKEN }}
