name: "Generate release note"
on:
  workflow_call:
    secrets:
        TOKEN:
          required: true
    inputs:
        tag:
            description: 'Tag version number (Eg: v0.1.0)'
            required: true
            type: string
    outputs:
        artifact-name:
            description: 'Release note artifact name'
            value: ${{ jobs.generate.outputs.artifact-name }}
jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.generate-release-notes.outputs.releasenoteartifact }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        name: Checkout 
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0
          ref: ${{ inputs.tag }}
      - id: generate-release-notes
        name: Generate Release Notes
        run: |
          echo "" > release-notes.txt
          export PREV_TAG=$(git tag --list 'v*' --sort=-version:refname | grep -E "v[0-9]+\.[0-9]+\.[0-9]+$" | head -n 2 | tail -n 1)
          export PREV_VERSION=${PREV_TAG//v}
          sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $PREV_VERSION/q;p" CHANGELOG.md >> release-notes.txt
          echo "releasenoteartifact=release-notes.txt" >> $GITHUB_OUTPUT
      - id: upload-release-notes
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.generate-release-notes.outputs.releasenoteartifact }}
          path: ${{ steps.generate-release-notes.outputs.releasenoteartifact }}
          retention-days: 1
