name: Sync Files
on:
  workflow_run:
    workflows: ["Plumber"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
        # Use specific commit SHA because the PR is not merged yet (https://github.com/BetaHuhn/repo-file-sync-action/pull/303)
      - name: Run Repo File Sync Action
        uses: BetaHuhn/repo-file-sync-action@2da9fa866f117b06abec3e4c61c5e96ef86c142f
        with:
          GH_PAT: ${{ secrets.SYNC_PAT }}
          CONFIG_PATH: sync.yml
          COMMIT_PREFIX: "chore:"
          GIT_EMAIL: "205752564+cloudavenue-bot@users.noreply.github.com"
          GIT_USERNAME: "cloudavenue-sync-bot"
