name: "Check Tag"
on:
  workflow_call:
    secrets:
        TOKEN:
          required: true
    inputs:
        tag:
            description: 'Tag version number (Eg: v0.1.0)'
            required: true
            type: string
jobs:
  check-tag-already-exists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout
        with:
          token: ${{ secrets.TOKEN }}
      - name: Check tag validity and existence
        env:
          TAG: ${{ inputs.tag }}
        run: |
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: invalid tag format. Expected vx.x.x" >&2
            exit 1
          fi
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists" >&2
            exit 1
          fi
